# scripts/convert_xlsx.py
import pandas as pd
import os

PREVIEWS_DIR = "previews"
INDEX_FILE = "docs/in_development_previews.md"
BASE_URL = "https://eckohaus.github.io/Angular_Momentum_Reaction_Engine_v2/previews"

def convert_xlsx(file, outfile):
    """Convert one .xlsx file into a read-only HTML preview."""
    xls = pd.ExcelFile(file)
    with open(outfile, "w", encoding="utf-8") as f:
        f.write(f"<h1>{os.path.basename(file)}</h1>")
        for sheet in xls.sheet_names:
            df = pd.read_excel(file, sheet_name=sheet)
            f.write(f"<h2>Sheet: {sheet}</h2>")
            f.write(df.to_html(index=False, escape=False))

def build_index(xlsx_files):
    """Regenerate docs/in_development_previews.md with source + preview links."""
    with open(INDEX_FILE, "w", encoding="utf-8") as f:
        f.write("# XLSX Preview Index\n\n")
        f.write("This file is auto-generated by GitHub Actions.\n")
        f.write("Do not edit manually — changes will be overwritten.\n\n")

        for file in sorted(xlsx_files):
            base = os.path.splitext(os.path.basename(file))[0]
            rel_source = os.path.relpath(file, "docs")  # relative path for repo browsing
            preview_url = f"{BASE_URL}/{base}.html"

            f.write(f"- **{os.path.basename(file)}**\n")
            f.write(f"  - [Source XLSX](../{rel_source})\n")
            f.write(f"  - [Preview (HTML)]({preview_url})\n\n")

if __name__ == "__main__":
    os.makedirs(PREVIEWS_DIR, exist_ok=True)

    xlsx_files = []
    for root, _, files in os.walk("data/spreadsheets"):
        for file in files:
            if file.endswith(".xlsx"):
                infile = os.path.join(root, file)
                base = os.path.splitext(file)[0]
                outfile = f"{PREVIEWS_DIR}/{base}.html"
                print(f"Converting {infile} → {outfile}")
                convert_xlsx(infile, outfile)
                xlsx_files.append(infile)

    # Rebuild index file
    build_index(xlsx_files)
    print(f"✅ Index updated: {INDEX_FILE}")
