import pandas as pd
import os
import urllib.parse
from collections import defaultdict

PREVIEWS_DIR = "previews"
INDEX_FILE = "docs/in_development_previews.md"
BASE_URL = "https://eckohaus.github.io/Angular_Momentum_Reaction_Engine_v2/previews"
GITHUB_BASE = "https://github.com/Eckohaus/Angular_Momentum_Reaction_Engine_v2/blob/master"
CHANGES_FILE = "changed_files.txt"

def convert_xlsx(file, outfile):
    """Convert one .xlsx file into a read-only HTML preview."""
    xls = pd.ExcelFile(file)
    with open(outfile, "w", encoding="utf-8") as f:
        f.write(f"<h1>{os.path.basename(file)}</h1>")
        for sheet in xls.sheet_names:
            df = pd.read_excel(file, sheet_name=sheet)
            f.write(f"<h2>Sheet: {sheet}</h2>")
            f.write(df.to_html(index=False, escape=False))

def build_index(grouped_files):
    """Write index file grouped by module/folder structure."""
    with open(INDEX_FILE, "w", encoding="utf-8") as f:
        f.write("# XLSX Preview Index\n\n")
        f.write("This file is auto-generated by GitHub Actions.\n")
        f.write("Do not edit manually — changes will be overwritten.\n\n")

        for module, files in sorted(grouped_files.items()):
            f.write(f"## {module}\n\n")
            for file in sorted(files):
                base = os.path.splitext(os.path.basename(file))[0]

                # GitHub blob URL for source XLSX
                repo_path = file.replace("\\", "/")  # normalize slashes
                source_url = f"{GITHUB_BASE}/{repo_path}"

                # URL-encode filename for HTML preview link
                preview_file = urllib.parse.quote(base) + ".html"
                preview_url = f"{BASE_URL}/{preview_file}"

                f.write(f"- **{os.path.basename(file)}**  \n")
                f.write(f"  - [Source XLSX]({source_url})  \n")
                f.write(f"  - [Preview (HTML)]({preview_url})\n\n")

if __name__ == "__main__":
    os.makedirs(PREVIEWS_DIR, exist_ok=True)
    xlsx_files = []
    changed = []
    grouped_files = defaultdict(list)

    for root, _, files in os.walk("data/spreadsheets/in_development"):
        for file in files:
            if file.endswith(".xlsx"):
                infile = os.path.join(root, file)
                base = os.path.splitext(file)[0]
                outfile = f"{PREVIEWS_DIR}/{base}.html"
                print(f"Converting {infile} → {outfile}")
                convert_xlsx(infile, outfile)
                xlsx_files.append(infile)
                changed.append(outfile)

                # Derive module name from folder path
                rel_root = os.path.relpath(root, "data/spreadsheets/in_development")
                module = rel_root.replace("/", " → ") if rel_root != "." else "Root"
                grouped_files[module].append(infile)

    # Rebuild index grouped by module/folder
    build_index(grouped_files)
    changed.append(INDEX_FILE)

    # Write list of changed files for commit message
    with open(CHANGES_FILE, "w") as f:
        f.write(", ".join(changed))
    print(f"✅ Index updated: {INDEX_FILE}")
    print(f"📄 Changed files listed in: {CHANGES_FILE}")
